language: go

go:
  - 1.9.x
  - "1.10"
  
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep


install:
  - ls -al 
  - dep ensure

script:
  - go test ./...

notifications:
  email:
    on_success: change
    on_failure: always
